# Use postgres/example user/password credentials
#version: '3.9'

services:
  db:
    image: postgres:17.6
    #user:  ${USEROS}:${USEROS}
    container_name: fsoapp-db
    restart: always
    # set shared memory limit when using docker-compose
    #shm_size: 128mb
    # or set shared memory limit when deploy via swarm stack
    networks:
      - fsoapp_network
    #ports:
    #  - 5433:5432
    volumes:
      - ./data:/var/lib/postgresql/data
    #env_file:
    #  - .env
    environment:
      #  POSTGRES_DB: ${POSTGRES_DB}
      #  POSTGRES_HOST: ${POSTGRES_HOST}
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
      PGDATA: ${PGDATA}
      #   POSTGRES_DB: fsoApp
  
  
  web:
    #build: .
    image: coglescode/fsomvc:main
    container_name: fsomvc
    restart: always
    networks:
      - fsoapp_network
    ports:
      - 8082:8080
    #env_file:
    #  - .env
    environment:
      POSTGRES_DB: ${POSTGRES_DB}
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
      POSTGRES_HOST: ${POSTGRES_HOST}
      POSTGRES_PORT: ${POSTGRES_PORT}
      #  ASPNETCORE_ENVIRONMENT: Development
      ConnectionString: ${ConnectionString}
    #depends_on:
    #  - db
  
  # For help with pgAdmin read the docs https://www.pgadmin.org/docs/pgadmin4/latest/index.html
  pgadmin:
    image: dpage/pgadmin4:9.6
    container_name: fsoapp-pgadmin
    restart: always
    ports:
      - 5051:80
    environment:
      PGADMIN_DEFAULT_EMAIL: ${YOUR_EMAIL}
      PGADMIN_DEFAULT_PASSWORD: ${YOUR_PASSWORD}

networks:
  dokploy-network:
    external: true